config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :attempts
  resources :subgenres
  resources :genres
  get 'quiz/index'

  resources :questions
  get 'admin/index'
  # get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]

  get 'admin' => 'admin#index'
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :quiz do
    get 'quiz' => 'quiz#index'
  end

  controller :scores do
    get 'scores/fetch/data' => :fetchdata
    get 'scores/oneanswer/:id' => :oneanswer
    get 'scores/numanswer/:id' => :numanswer
    get 'scores/fetch/not' => :notattempted
    get 'scores/genre/:id' => :genleaderboard
    get 'scores/subgenre/:id' => :subgenleaderboard
    get 'scores/update/state' => :updatestate
  end

  controller :questions do
    get 'questions/find/:sid/:gid' => :fromsub 
    get 'questionstp/' => :timepass    
  end

  controller :attempts do
    get 'attempts/find/add' => :showques
    get 'attempts/check/change' => :check
  end

  resources :users
  root 'admin#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subgenre.rb
class Subgenre < ApplicationRecord
	validates	:name, uniqueness: true
end

app/controllers/subgenres_controller.rb
class SubgenresController < ApplicationController
  before_action :set_subgenre, only: [:show, :edit, :update, :destroy]

  # GET /subgenres
  # GET /subgenres.json
  def index
    if session[:user_id] and  User.find_by(id: session[:user_id]).name == "admin"
      @subgenres = Subgenre.all
    elsif session[:user_id]
    #  @users = User.all
      redirect_to quiz_url
    else
      redirect_to login_url
    end  
  end

  # GET /subgenres/1
  # GET /subgenres/1.json
  def show
  end

  # GET /subgenres/new
  def new
    if session[:user_id] and  User.find_by(id: session[:user_id]).name == "admin"
      @subgenre = Subgenre.new
    elsif session[:user_id]
    #  @users = User.all
      redirect_to quiz_url
    else
      redirect_to login_url
    end  
  end

  # GET /subgenres/1/edit
  def edit
  end

  # POST /subgenres
  # POST /subgenres.json
  def create
    print "\n\n"
    print subgenre_params
    print "\n\n"  
    @subgenre = Subgenre.new(subgenre_params)

    respond_to do |format|
      if @subgenre.save
        format.html { redirect_to @subgenre, notice: 'Subgenre was successfully created.' }
        format.json { render :show, status: :created, location: @subgenre }
      else
        format.html { render :new }
        format.json { render json: @subgenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subgenres/1
  # PATCH/PUT /subgenres/1.json
  def update
    respond_to do |format|
      if @subgenre.update(subgenre_params)
        format.html { redirect_to @subgenre, notice: 'Subgenre was successfully updated.' }
        format.json { render :show, status: :ok, location: @subgenre }
      else
        format.html { render :edit }
        format.json { render json: @subgenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subgenres/1
  # DELETE /subgenres/1.json
  def destroy
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      subgenre = Subgenre.find_by(id: params[:id])
      Question.where(subgenre: subgenre.name).destroy_all
      @subgenre.destroy
      respond_to do |format|
        format.html { redirect_to subgenres_url, notice: 'Subgenre was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to login_url, notice: "Please login as admin"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subgenre
      @subgenre = Subgenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subgenre_params
      params.require(:subgenre).permit(:name, :genrename)
    end
end

app/helpers/subgenres_helper.rb
module SubgenresHelper
end

app/views/subgenres/_form.html.erb
<%= form_with(model: subgenre, local: true) do |form| %>
  <% if subgenre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subgenre.errors.count, "error") %> prohibited this subgenre from being saved:</h2>

      <ul>
      <% subgenre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subgenre_name %>
  </div>

  <div class="field">
    <%= form.label :genrename %>
    <%= form.collection_select :genrename, Genre.all, :name, :name, :prompt => "Select a genre" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subgenres/edit.html.erb
<h1>Editing Subgenre</h1>

<%= render 'form', subgenre: @subgenre %>

<%= link_to 'Show', @subgenre %> |
<%= link_to 'Back', subgenres_path %>

app/views/subgenres/index.html.erb
<body style="margin:0px;">

<div style="height:100px;font-size:200%;background-color:green ;width:100%;border-bottom: 1px solid black">
<h1  style="padding-left:50px;padding-top: 40px; color:white">Subgenres</h1>
</div>

<p id="notice"><%= notice %></p>

<table style="margin-left: 100px;margin-top: 100px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Genrename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subgenres.each do |subgenre| %>
      <tr>
        <td><%= subgenre.name %></td>
        <td><%= subgenre.genrename %></td>
        <td><%= link_to 'Show', subgenre %></td>
        <td><%= link_to 'Edit', edit_subgenre_path(subgenre) %></td>
        <td><%= link_to 'Destroy', subgenre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div style="margin-left: 100px;">
<%= link_to 'New Subgenre', new_subgenre_path %>
<%= link_to 'Back', '/admin' %>
</div>

app/views/subgenres/new.html.erb
<body style="margin:0px;">

<div style="height:100px;font-size:200%;background-color:green ;width:100%;border-bottom: 1px solid black">
<h1  style="padding-left:50px;padding-top: 40px; color:white">New Subgenre</h1>
</div>

<div style="margin-top:100px;margin-left: 100px;">
<%= render 'form', subgenre: @subgenre %>

<%= link_to 'Back', '/admin' %>
</div>

app/views/subgenres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subgenre.name %>
</p>

<p>
  <strong>Genrename:</strong>
  <%= @subgenre.genrename %>
</p>

<%= link_to 'Edit', edit_subgenre_path(@subgenre) %> |
<%= link_to 'Back', subgenres_path %>