config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :attempts
  resources :subgenres
  resources :genres
  get 'quiz/index'

  resources :questions
  get 'admin/index'
  # get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]

  get 'admin' => 'admin#index'
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :quiz do
    get 'quiz' => 'quiz#index'
  end

  controller :scores do
    get 'scores/fetch/data' => :fetchdata
    get 'scores/oneanswer/:id' => :oneanswer
    get 'scores/numanswer/:id' => :numanswer
    get 'scores/fetch/not' => :notattempted
    get 'scores/genre/:id' => :genleaderboard
    get 'scores/subgenre/:id' => :subgenleaderboard
    get 'scores/update/state' => :updatestate
  end

  controller :questions do
    get 'questions/find/:sid/:gid' => :fromsub 
    get 'questionstp/' => :timepass    
  end

  controller :attempts do
    get 'attempts/find/add' => :showques
    get 'attempts/check/change' => :check
  end

  resources :users
  root 'admin#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attempt.rb
class Attempt < ApplicationRecord
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :set_attempt, only: [:show, :edit, :update, :destroy]

  def showques
    q = Attempt.where(:uid => session[:user_id], :state => 0)
    if q.present?
      ques = Question.find_by(id: q[0].qid)
      ques.correctoption = ""
    else
      if Attempt.where(:uid => session[:user_id]).reverse.present?
        x = Attempt.where(:uid => session[:user_id]).reverse
        s = Question.find_by(:id => x[0].qid)
        z = Question.where(:subgenre => s.subgenre).length
        a = Attempt.where(:uid => session[:user_id]).reverse
        arr = Array.new
        for i in 0..z-1
          w = Array.new
          w << i << a[i].success
          arr << w
        end
        print arr
        ques = {array: arr}
      end
    end
    render json: ques
  end

  def check
    # print params
    ques = Question.find(params[:quizid])
    a = Attempt.find_by(:uid => session[:user_id], :state => 0, :qid => params[:quizid])
    if ques.correctoption.eql? params[:quizanswer]
      abc = Score.find_by(uid: session[:user_id], state: 0)
      xy = abc.sid
      za = abc.score
      we = abc.lifeone
      wq = abc.lifetwo
      abc.update({"uid" => session[:user_id], "sid" => xy, "state" => 0, "score" => za+10, "lifeone" => we, "lifetwo" => wq})
      a.update({"uid" => session[:user_id], "qid" => params[:quizid], "state" => 1, "success" => 1})
    else
      a.update({"uid" => session[:user_id], "qid" => params[:quizid], "state" => 1, "success" => 0})
    end
  end

  # GET /attempts
  # GET /attempts.json
  def index
    if session[:user_id] and  User.find_by(id: session[:user_id]).name == "admin"
      @attempts = Attempt.all  
    elsif session[:user_id]
    #  @users = User.all
      redirect_to quiz_url
    else
      redirect_to login_url
    end
    
  end

  # GET /attempts/1
  # GET /attempts/1.json
  def show
  end

  # GET /attempts/new
  def new
    @attempt = Attempt.new
  end

  # GET /attempts/1/edit
  def edit
  end

  # POST /attempts
  # POST /attempts.json
  def create
    @attempt = Attempt.new(attempt_params)

    respond_to do |format|
      if @attempt.save
        format.html { redirect_to @attempt, notice: 'Attempt was successfully created.' }
        format.json { render :show, status: :created, location: @attempt }
      else
        format.html { render :new }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attempts/1
  # PATCH/PUT /attempts/1.json
  def update
    respond_to do |format|
      if @attempt.update(attempt_params)
        format.html { redirect_to @attempt, notice: 'Attempt was successfully updated.' }
        format.json { render :show, status: :ok, location: @attempt }
      else
        format.html { render :edit }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempts/1
  # DELETE /attempts/1.json
  def destroy
    @attempt.destroy
    respond_to do |format|
      format.html { redirect_to attempts_url, notice: 'Attempt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_params
      params.require(:attempt).permit(:uid, :qid, :success, :state)
    end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/views/attempts/index.html.erb
<body style="margin:0px;">

<div style="height:100px;font-size:200%;background-color:green ;width:100%;border-bottom: 1px solid black">
<h1  style="padding-left:50px;padding-top: 40px; color:white">Scores</h1>
</div>

<p id="notice"><%= notice %></p>

<table style="margin-left: 100px;margin-top: 100px;">
  <thead>
    <tr>
      <th>Uid</th>
      <th>Qid</th>
      <th>Success</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <td><%= attempt.uid %></td>
        <td><%= attempt.qid %></td>
        <td><%= attempt.success %></td>
        <td><%= attempt.state %></td>
        <td><%= link_to 'Show', attempt %></td>
        <td><%= link_to 'Edit', edit_attempt_path(attempt) %></td>
        # <td><%= link_to 'Destroy', attempt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--%= link_to 'New Attempt', new_attempt_path %-->
<div style="margin-left: 100px">
<%= link_to 'Back', '/admin' %>
</div>

app/views/attempts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @attempt.uid %>
</p>

<p>
  <strong>Qid:</strong>
  <%= @attempt.qid %>
</p>

<p>
  <strong>Success:</strong>
  <%= @attempt.success %>
</p>

<p>
  <strong>State:</strong>
  <%= @attempt.state %>
</p>

<%= link_to 'Edit', edit_attempt_path(@attempt) %> |
<%= link_to 'Back', attempts_path %>